apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tcg.fullname" . }}
  labels: {{- include "tcg.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "tcg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "tcg.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef: { name: mysql-credentials, key: password }
          readinessProbe:
            httpGet: { path: /readyz, port: 8000 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
