apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tcg.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{- include "tcg.selectorLabels" . | nindent 6 }}
